version: "3.8"

services:
  zookeeper:
    image: zookeeper:3.8.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${MACHINE_IP}
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181/kafka
    depends_on:
      - zookeeper

  pinot-controller:
    image: anduin/pinot:0.11.0.2
    command: "StartController -zkAddress zookeeper:2181"
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./configs/pinot:/config
      - ./input:/input
    depends_on:
      - zookeeper

  pinot-broker:
    image: anduin/pinot:0.11.0.2
    command: "StartBroker -zkAddress zookeeper:2181"
    restart: unless-stopped
    depends_on:
      - pinot-controller

  pinot-server:
    image: anduin/pinot:0.11.0.2
    command: "StartServer -zkAddress zookeeper:2181"
    restart: unless-stopped
    depends_on:
      - pinot-broker

  # jobmanager:
  #   image: flink:1.15.1
  #   command: jobmanager
  #   volumes:
  #     - ./libs:/opt/flink/connector-libs
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       parallelism.default: 2

  # taskmanager:
  #   image: flink:1.15.1
  #   command: taskmanager
  #   environment:
  #     - |
  #       FLINK_PROPERTIES=
  #       jobmanager.rpc.address: jobmanager
  #       taskmanager.numberOfTaskSlots: 2
  #       parallelism.default: 2
  #   depends_on:
  #     - jobmanager
